### ISSUE TITLE
Sidenotes

### ISSUE THREAD

**Issue by EricMFink** [manunamz/jekyll-bonsai#6]
I'm having trouble getting sidenotes to work. I followed the directions [here](https://manunamz.github.io/jekyll-bonsai/entry/95a80b4157/). But this is how it renders in html:

![Screenshot from 2022-12-06 13-14-28](https://user-images.githubusercontent.com/17663411/205989844-33bd7748-df76-48cb-b53a-33d19ce24c80.png)

The links point to 404. 

Is there some additional plugin or gem required to make sidenotes work?

**Comment by manunamz** [comment]
Sidenotes were removed a while ago, but I have released the gem for you [here](https://rubygems.org/gems/jekyll-sidenotes); repo is [here](https://github.com/manunamz/jekyll-sidenotes). I have not tested the standalone gem, so let me know if there are any issues with it.

Also worthy of note: The sidenotes doc you linked to is an older version of the template. The up-to-date version is [here](https://jekyll-bonsai.netlify.app/entry/e4dc466bc6/).

Do you mind my asking how you get to the old site? I need to cleanup the old link -- wherever it is.

**Comment by EricMFink** [comment]
Thank you. I'll give this gem a try. 

I found the sidenotes doc through a Google search for "jekyll sidenotes".

**Comment by manunamz** [comment]
Sounds good. Let me know.

As a sidenote (hehe), I also found [this](https://github.com/clayh53/tufte-jekyll) while deploying the gem. It's old, but it looks like they still maintain it.
